fix(prog): Download and run PS7 FSBL file first.
Running the FSBL is blocking the DDR.
Trying to program the PS7 FW afterwards (or retrying to program the
FSBL) will fail with the following error:
Exception: APB AP transaction error, DAP status 0xF0000021

This means that there is and outstanding AXI transaction in the bus, causing the PS to hang.
https://adaptivesupport.amd.com/s/question/0D52E00007G0sGASAZ/apb-ap-transaction-error-dap-status-f0000021-on-application-launch?language=en_US